{% extends "layouts/template.phtml" %}
{% block title %}Slim 3{% endblock %}

{% block styles %}
    {{ parent() }}
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
{% endblock %}

{% block content %}
<div class="text-center">
    <h1>Listado de Empledos</h1>
    <div>con Slim MicroFramework</div>
    <p>Try <a href="{{ path_for('listado-empleados-get') }}">Ingresar al listado</a></p>
</div>
{% endblock %}