<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Navbar Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="container">

    <!-- Static navbar -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Developer SAC</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">Home</a></li>
                    <li><a href="/listado">Listado</a></li>
                </ul>
                <form class="navbar-form navbar-left" method="post">
                    <div class="form-group">
                        <input type="email" required name="email" class="form-control" placeholder="Buscar por E-mail">
                    </div>
                    <button type="submit" class="btn btn-default">Buscar</button>
                    <input type="hidden" name="csrf_name" value="<?= $csrfToken['csrf_name'] ?>">
                    <input type="hidden" name="csrf_value" value="<?= $csrfToken['csrf_value'] ?>">
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="../navbar-fixed-top/">Servicio XML</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>

    <h2>Listado de Empledos</h2>
    <?php if (isset($returnList)) : ?>
        <a href="/listado" class="btn btn-success">Volver al Listado</a>
    <?php endif ?>
    <table class="table  table-hover table-condensed">
        <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Position</th>
            <th>Salary</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($empleados as $empleado) :?>
            <tr>
                <td><?= $empleado->name ?></td>
                <td><?= $empleado->email ?></td>
                <td><?= $empleado->position ?></td>
                <td><?= $empleado->salary ?></td>
                <td>
                    <button class="btn btn-sm btn-primary" data-id="<?= $empleado->id ?>" data-toggle="modal" data-target="#modalEmpleadoDetalles">
                        Ver detalles
                    </button>
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>

    <div class="modal fade" id="modalEmpleadoDetalles" tabindex="-1" role="dialog" aria-labelledby="modalEmpleadoDetalles">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel">Detalles del Empleado</h4>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
    $('#modalEmpleadoDetalles').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var id = button.data('id');
        if (id) {
            var modal = $(this);
            $.post( "/empleado/ver/"+id, {
                'csrf_name': '<?= $csrfToken['csrf_name'] ?>',
                'csrf_value': '<?= $csrfToken['csrf_value'] ?>'
            }).done(function(data){
                var ol = $('<ol></ol>');
                Object.entries(data).map(function(item) {
                    if (item.length === 2) {
                        if (item[0] == "skills") {
                            var ul = $('<ul>');
                            if (item[1].length > 0) {
                                item[1].map(function(sk){
                                    ul.append('<li><strong>'+sk.skill+'</strong></li>');
                                });
                            }
                            ol.append('<li>'+item[0] + ': <ul>'+ul.html()+'</ul></li>')
                        } else {
                            ol.append('<li>'+item[0] + ': <strong>'+item[1]+'</strong></li>')
                        }
                    }
                });
                modal.find('.modal-body').append(ol);
            });
        }

    })
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>