<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{% block title %}{% endblock %}</title>
        {% block styles %}
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
            <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->
        {% endblock %}
    {% endblock %}
</head>

<body>
<div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            {% block menu %}
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Developer SAC</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="{{ base_url() == '/' ? 'active' : '' }}"><a href="{{ path_for('home') }}">Home</a></li>
                        <li class="{{ base_url() == '/listado' ? 'active' : '' }}"><a href="{{ path_for('listado-empleados-get') }}">Listado</a></li>
                    </ul>
                    <form class="navbar-form navbar-left" method="post">
                        <div class="form-group">
                            <input type="text" required name="email" class="form-control" placeholder="Buscar por E-mail">
                        </div>
                        <button type="submit" class="btn btn-default">Buscar</button>
                        <input type="hidden" name="csrf_name" value="{{ csrfToken['csrf_name'] }}">
                        <input type="hidden" name="csrf_value" value="{{ csrfToken['csrf_value'] }}">
                    </form>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/v1/wsdl">Servicio XML</a></li>
                    </ul>
                </div>
            {% endblock %}
        </div>
    </nav>
    {% block content %}{% endblock %}

</div>
{% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>